#!/usr/bin/env node
/**
 * Generate `src/design/tokens.css` from `src/design/tokens.ts`.
 *
 * Produces:
 *   :root, [data-theme="dark"]  — dark theme variables (default)
 *   [data-theme="light"]        — light theme overrides
 *   .type-*                     — type-token classes (per B3 §2.5)
 *
 * Idempotent. Safe to re-run; the generated file is committed and ESLint's
 * raw-px / raw-hex rule allows tokens.css as the single emission target.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const ROOT = resolve(dirname(__filename), '..');
const TOKENS_TS = resolve(ROOT, 'src/design/tokens.ts');
const OUT = resolve(ROOT, 'src/design/tokens.css');

/**
 * Token loading strategy (per PR #6 cycle-1 review F14):
 *   1. Primary: dynamic import of tokens.ts. Works on Node ≥22.6 with the
 *      built-in TypeScript stripping (no external transpiler needed).
 *   2. Fallback: a strict literal-extractor. Strict means: it MUST round-trip
 *      via JSON.parse and the parsed object MUST contain every documented
 *      top-level key from the schema below. If either fails the script exits
 *      non-zero — silent misparse is impossible.
 *
 * To run on Node <22.6, install the dynamic-import hook the user prefers
 * (e.g., `node --import tsx/esm`); the codegen will pick it up automatically.
 */
const REQUIRED_TOP_LEVEL_KEYS = [
  'color',
  'space',
  'radius',
  'size',
  'border',
  'breakpoint',
  'motion',
  'type',
  'shadow',
];

const tokensModule = await import(pathToFileURL(TOKENS_TS).href).catch(() => null);
let tokens;
if (tokensModule && tokensModule.tokens) {
  tokens = tokensModule.tokens;
} else {
  // Strict fallback: extract `tokens = { ... } as const` via brace-walk +
  // JSON-strict transformation. Verifies via top-level-key presence.
  const { readFileSync } = await import('node:fs');
  const src = readFileSync(TOKENS_TS, 'utf8');
  const start = src.indexOf('export const tokens =');
  if (start < 0) throw new Error('codegen-tokens: tokens export not found');
  const objStart = src.indexOf('{', start);
  let depth = 0;
  let end = -1;
  for (let i = objStart; i < src.length; i++) {
    const ch = src[i];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end < 0) throw new Error('codegen-tokens: failed to balance braces');
  const literal = src.slice(objStart, end);
  // Strip block comments, line comments (only when not inside a string), and
  // trailing commas (JSON-strict).
  const stripped = literal
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:"'])\/\/.*$/gm, '$1')
    .replace(/,(\s*[}\]])/g, '$1');
  // Quote unquoted object keys: alphanumeric AND numeric (e.g. `1: 2,`).
  const jsonish = stripped.replace(
    /([{,]\s*)([A-Za-z_$][A-Za-z0-9_$-]*|\d+)\s*:/g,
    (_, lead, key) => `${lead}"${key}":`,
  );
  // Single → double quotes (no nested escapes in our tokens).
  const json = jsonish.replace(/'([^']*)'/g, '"$1"');
  let parsed;
  try {
    parsed = JSON.parse(json);
  } catch (err) {
    throw new Error(
      `codegen-tokens: fallback JSON parse failed (${err.message}). ` +
        `Run with Node ≥22.6 (built-in TS stripping) or install a TS loader.`,
    );
  }
  for (const key of REQUIRED_TOP_LEVEL_KEYS) {
    if (!(key in parsed)) {
      throw new Error(
        `codegen-tokens: fallback parser missing top-level key "${key}". ` +
          `Refusing to emit a partial tokens.css. ` +
          `Run with Node ≥22.6 (built-in TS stripping) or install a TS loader.`,
      );
    }
  }
  tokens = parsed;
}

const lines = [];
const banner = [
  '/* GENERATED by scripts/codegen-tokens.mjs from src/design/tokens.ts.',
  '   Do not edit by hand. Re-run `pnpm --filter @trail/ui run tokens:gen`.',
  '   Spec: docs/specs/phase-2-design-system.md §11. */',
  '',
];
lines.push(...banner);

// Helper: format a CSS variable value (keep numbers as px where applicable).
const px = (n) => `${n}px`;

// ------------------------------- primitives -------------------------------
lines.push(':root, [data-theme="dark"] {');
for (const [k, v] of Object.entries(tokens.color.ink)) lines.push(`  --ink-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.color.copper)) lines.push(`  --copper-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.color.risk)) lines.push(`  --risk-${k}: ${v.dark};`);
for (const [k, v] of Object.entries(tokens.color.riskBg)) lines.push(`  --risk-${k}-bg: ${v.dark};`);
lines.push(`  --trail-line: ${tokens.color.trail.line.dark};`);
lines.push(`  --trail-line-dim: ${tokens.color.trail.lineDim.dark};`);

// Spacing
for (const [k, v] of Object.entries(tokens.space)) lines.push(`  --space-${k}: ${px(v)};`);
// Radius
for (const [k, v] of Object.entries(tokens.radius)) {
  lines.push(`  --radius-${k}: ${k === 'full' ? `${v}px` : px(v)};`);
}
// Size
for (const [k, v] of Object.entries(tokens.size)) {
  const kebab = k.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
  lines.push(`  --size-${kebab}: ${px(v)};`);
}
// Border widths (kebab-case keys; --border-width-focus-ring etc.)
for (const [k, v] of Object.entries(tokens.border)) {
  const kebab = k.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
  lines.push(`  --border-width-${kebab}: ${px(v)};`);
}
// Breakpoints
for (const [k, v] of Object.entries(tokens.breakpoint)) {
  lines.push(`  --breakpoint-${k}: ${px(v)};`);
}
// Type sizes (so global.css can reference --font-size-ui rather than raw 14px).
for (const [name, t] of Object.entries(tokens.type)) {
  lines.push(`  --font-size-${name}: ${px(t.size)};`);
}
// Motion
for (const [k, v] of Object.entries(tokens.motion.duration)) lines.push(`  --motion-${k}: ${v}ms;`);
for (const [k, v] of Object.entries(tokens.motion.ease)) lines.push(`  --ease-${k}: ${v};`);
// Shadow
lines.push(`  --shadow-pop: ${tokens.shadow.pop.dark};`);
lines.push(`  --shadow-toast: ${tokens.shadow.toast.dark};`);
lines.push(`  --shadow-warning: ${tokens.shadow.warning};`);

// Semantic tokens (dark)
const darkSemantic = {
  '--bg': 'var(--ink-950)',
  '--surface': 'var(--ink-900)',
  '--surface-raised': 'var(--ink-850)',
  '--border-subtle': 'var(--ink-800)',
  '--border-strong': 'var(--ink-700)',
  '--text-primary': 'var(--ink-200)',
  '--text-secondary': 'var(--ink-400)',
  '--text-tertiary': 'var(--ink-500)',
  '--text-on-accent': 'var(--ink-1000)',
  '--accent': 'var(--copper-400)',
  '--accent-hover': 'var(--copper-500)',
  '--accent-text': 'var(--copper-300)',
  '--focus-ring': 'var(--copper-400)',
  '--focus-ring-offset': 'var(--ink-950)',
  '--link': 'var(--copper-300)',
  '--link-hover': 'var(--copper-400)',
};
for (const [k, v] of Object.entries(darkSemantic)) lines.push(`  ${k}: ${v};`);

lines.push('}');
lines.push('');

// Light theme overrides
lines.push('[data-theme="light"] {');
for (const [k, v] of Object.entries(tokens.color.paper)) lines.push(`  --paper-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.color.risk)) lines.push(`  --risk-${k}: ${v.light};`);
for (const [k, v] of Object.entries(tokens.color.riskBg)) lines.push(`  --risk-${k}-bg: ${v.light};`);
lines.push(`  --trail-line: ${tokens.color.trail.line.light};`);
lines.push(`  --trail-line-dim: ${tokens.color.trail.lineDim.light};`);
lines.push(`  --shadow-pop: ${tokens.shadow.pop.light};`);
lines.push(`  --shadow-toast: ${tokens.shadow.toast.light};`);

const lightSemantic = {
  '--bg': 'var(--paper-50)',
  '--surface': 'var(--paper-100)',
  '--surface-raised': 'var(--paper-200)',
  '--border-subtle': 'var(--paper-300)',
  '--border-strong': 'var(--paper-400)',
  '--text-primary': 'var(--paper-900)',
  '--text-secondary': 'var(--paper-700)',
  '--text-tertiary': 'var(--paper-600)',
  '--text-on-accent': 'var(--paper-50)',
  '--accent': 'var(--copper-600)',
  '--accent-hover': 'var(--copper-700)',
  '--accent-text': 'var(--copper-700)',
  '--focus-ring': 'var(--copper-600)',
  '--focus-ring-offset': 'var(--paper-50)',
  '--link': 'var(--copper-600)',
  '--link-hover': 'var(--copper-700)',
};
for (const [k, v] of Object.entries(lightSemantic)) lines.push(`  ${k}: ${v};`);

lines.push('}');
lines.push('');

// ------------------------------- type tokens ------------------------------
lines.push('/* Type tokens — opsz axis pinned per token (B3 §2.5). */');
for (const [name, t] of Object.entries(tokens.type)) {
  const cls = `.type-${name}`;
  const isNewsreader = t.family === 'Newsreader';
  const fam =
    t.family === 'Newsreader'
      ? '"Newsreader", serif'
      : t.family === 'Commit Mono'
        ? '"Commit Mono", monospace'
        : '"Public Sans", sans-serif';
  const variation = isNewsreader
    ? `font-variation-settings: "opsz" ${t.opsz}, "wght" ${t.weight};`
    : null;
  const upper = t.uppercase ? 'text-transform: uppercase;' : null;
  const decls = [
    `font-family: ${fam};`,
    `font-size: ${px(t.size)};`,
    `line-height: ${t.lineHeight};`,
    `font-weight: ${t.weight};`,
    `letter-spacing: ${t.tracking};`,
    variation,
    upper,
  ]
    .filter(Boolean)
    .map((d) => `  ${d}`)
    .join('\n');
  lines.push(`${cls} {`);
  lines.push(decls);
  lines.push('}');
}
lines.push('');

// ----------------------------- focus + motion -----------------------------
lines.push(`:focus-visible {
  outline: none;
  box-shadow:
    0 0 0 2px var(--focus-ring-offset),
    0 0 0 4px var(--focus-ring);
}`);
lines.push('');
lines.push(`@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
  }
}`);
lines.push('');

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, lines.join('\n'), 'utf8');
console.log(`tokens-codegen: wrote ${OUT}`);
